---
name: Padre-Plugin-Perl6
version: 0.62
author:
  - Ahmad M. Zawawi and Gabor Szabo
abstract: Padre plugin for Perl 6
license: perl
resources:
  homepage: http://padre.perlide.org/
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Padre-Plugin-Perl6/
build_requires:
  Locale::Msgfmt: 0.14
  Test::Exception: 0.27
  Test::More: 0.86
requires:
  App::Grok: 0.19
  Archive::Zip: 1.30
  Class::XSAccessor: 1.02
  File::Which: 0.05
  HTTP::Status: 5.817
  Net::HTTP: 5.831
  Padre: 0.52
  Perl6::Doc: 0.45
  Perl6::Refactor: 0
  Syntax::Highlight::Perl6: 0.77
  URI: 1.37
  perl: 5.010
configure_requires:
  Module::Build: 0.35
provides:
  Padre::Plugin::Perl6:
    file: lib/Padre/Plugin/Perl6.pm
    version: 0.62
  Padre::Plugin::Perl6::Perl6Colorizer:
    file: lib/Padre/Plugin/Perl6/Perl6Colorizer.pm
    version: 0.62
  Padre::Plugin::Perl6::Perl6Document:
    file: lib/Padre/Plugin/Perl6/Perl6Document.pm
    version: 0.62
  Padre::Plugin::Perl6::Perl6HelpProvider:
    file: lib/Padre/Plugin/Perl6/Perl6HelpProvider.pm
    version: 0.62
  Padre::Plugin::Perl6::Perl6OutlineTask:
    file: lib/Padre/Plugin/Perl6/Perl6OutlineTask.pm
    version: 0.62
  Padre::Plugin::Perl6::Perl6QuickFixProvider:
    file: lib/Padre/Plugin/Perl6/Perl6QuickFixProvider.pm
    version: 0.62
  Padre::Plugin::Perl6::Perl6StdColorizer:
    file: lib/Padre/Plugin/Perl6/Perl6StdColorizer.pm
    version: 0.62
  Padre::Plugin::Perl6::Perl6StdColorizerTask:
    file: lib/Padre/Plugin/Perl6/Perl6StdColorizerTask.pm
    version: 0.62
  Padre::Plugin::Perl6::Perl6SyntaxCheckerTask:
    file: lib/Padre/Plugin/Perl6/Perl6SyntaxCheckerTask.pm
    version: 0.62
  Padre::Plugin::Perl6::Preferences:
    file: lib/Padre/Plugin/Perl6/Preferences.pm
    version: 0.62
  Padre::Plugin::Perl6::UpdateDialog:
    file: lib/Padre/Plugin/Perl6/UpdateDialog.pm
    version: 0.62
  Padre::Plugin::Perl6::UpdateTask:
    file: lib/Padre/Plugin/Perl6/UpdateTask.pm
    version: 0.62
  Padre::Plugin::Perl6::Util:
    file: lib/Padre/Plugin/Perl6/Util.pm
    version: 0.62
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
