---
name: Padre-Plugin-Perl6
version: 0.57
author:
  - Ahmad M. Zawawi and Gabor Szabo
abstract: Padre plugin for Perl 6
license: perl
resources:
  homepage: http://padre.perlide.org/
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Padre-Plugin-Perl6/
requires:
  App::Grok: 0.19
  Class::XSAccessor: 1.02
  File::Which: 0.05
  Padre: 0.44
  Perl6::Refactor: 0
  Syntax::Highlight::Perl6: 0.71
  URI: 1.37
  perl: 5.010
build_requires:
  Locale::Msgfmt: 0.14
  Test::Exception: 0.27
  Test::More: 0.86
provides:
  Padre::Plugin::Perl6:
    file: lib/Padre/Plugin/Perl6.pm
    version: 0.57
  Padre::Plugin::Perl6::Perl6Colorizer:
    file: lib/Padre/Plugin/Perl6/Perl6Colorizer.pm
    version: 0.57
  Padre::Plugin::Perl6::Perl6Document:
    file: lib/Padre/Plugin/Perl6/Perl6Document.pm
    version: 0.57
  Padre::Plugin::Perl6::Perl6OutlineTask:
    file: lib/Padre/Plugin/Perl6/Perl6OutlineTask.pm
    version: 0.57
  Padre::Plugin::Perl6::Perl6StdColorizer:
    file: lib/Padre/Plugin/Perl6/Perl6StdColorizer.pm
    version: 0.57
  Padre::Plugin::Perl6::Perl6StdColorizerTask:
    file: lib/Padre/Plugin/Perl6/Perl6StdColorizerTask.pm
    version: 0.57
  Padre::Plugin::Perl6::Perl6SyntaxCheckerTask:
    file: lib/Padre/Plugin/Perl6/Perl6SyntaxCheckerTask.pm
    version: 0.57
  Padre::Plugin::Perl6::Preferences:
    file: lib/Padre/Plugin/Perl6/Preferences.pm
    version: 0.57
  Padre::Plugin::Perl6::Util:
    file: lib/Padre/Plugin/Perl6/Util.pm
    version: 0.57
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
