---
abstract: 'Padre plugin for Perl6'
author:
  - 'Gabor Szabo'
build_requires:
  Test::Exception: 0.27
  Test::More: 0.47
  Test::NeedsDisplay: 1.05
  Test::NoWarnings: 0.084
configure_requires:
  ExtUtils::MakeMaker: 6.50
distribution_type: module
generated_by: 'Module::Install version 0.81'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Padre-Plugin-Perl6
no_index:
  directory:
    - inc
    - t
requires:
  File::Which: 0.05
  IPC::Run3: 0.042
  Padre: 0.25
  Readonly: 1.03
  Syntax::Highlight::Perl6: 0.040
  URI: 1.37
  perl: 5.010
resources:
  bugtracker: http://padre.perlide.org/
  homepage: http://padre.perlide.org/
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Padre-Plugin-Perl6
version: 0.27
